### ISSUE TITLE
[Help] Get error to compile in VS Code

### ISSUE THREAD

**Issue by SuEuMesma** [JereKuusela/valheim-dev#48]
I'm not very good at programming but I'm trying to make some modifications to the MOD using VS code. But when trying to compile, I receive the following errors:

```
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error : BinaryFormatter serialization and deserialization are disabled within this application. See  
https://aka.ms/binaryformatter for more information.
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serial 
izationStream, Object graph)
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at ILRepacking.Steps.ResourcesRepackStep.GenerateRepackListResource(List`1 repackList)    
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at ILRepacking.Steps.ResourcesRepackStep.Perform()
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at ILRepacking.ILRepack.Repack()
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at ILRepack.Lib.MSBuild.ILRepack.Execute()

FALHA da compilação.

C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error : BinaryFormatter serialization and deserialization are disabled within this application. See  
https://aka.ms/binaryformatter for more information.
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serial 
izationStream, Object graph)
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at ILRepacking.Steps.ResourcesRepackStep.GenerateRepackListResource(List`1 repackList)    
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at ILRepacking.Steps.ResourcesRepackStep.Perform()
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at ILRepacking.ILRepack.Repack()
C:\valheim-dev-main\ServerDevcommands\ServerDevcommands.csproj(14,7): error :    at ILRepack.Lib.MSBuild.ILRepack.Execute()
    0 Aviso(s)
    1 Erro(s)
```

Can anyone tell me the way to solve it? I've searched a few places but haven't been successful.
Note: Previously I used Visual Studio and was able to compile the MOD normally, however, something seems to be missing in VS Code.

**Comment by JereKuusela** [comment]
Hello,

I'm using dotnet 7.0.400. So if you use version 8 or 9, maybe that causes something.

**Comment by SuEuMesma** [comment]
> Hello,
> 
> I'm using dotnet 7.0.400. So if you use version 8 or 9, maybe that causes something.

I followed your tip and now it works perfect. Thank you very much!
